name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: uv sync

    - name: Lint
      run: uv run ruff check --ignore E501 .

    - name: Format Check
      run: uv run ruff format --check .

    - name: Run tests
      run: uv run pytest
